### PR TITLE
`limit` and `offset` for #find_all

### PR DESCRIPTION
**Pull request by fredwu**
Added `limit` and `offset` for `#find_all` :-)

### CODE REVIEW

**Comment by fredwu** [comment]
cc @ianwhite @josevalim just in case. :)

**Comment by ianwhite** [comment]
Hi Fred,
I think this is a good addition (pagintation FTW!).  I'll merge it in when I'm next working at my computer (sometime tomorrow probably).  Unless José has any objections.

**Comment by josevalim** [comment]
Fine for me. :)

**Comment by ianwhite** [comment]
Thanks Fred :D

**Pull request merged**
