### PR TITLE
MongoMapper 0.9.0 Support

### PR DESCRIPTION
**Pull request by icaruswings**
Hi, I added MongoMapper support to my own fork of orm_adapter.
now that MM works with ActiveModel it'd be great if we could get an MM adapter into the official version.

cheers
Luke

### CODE REVIEW

**Comment by ghost** [comment]
dont be scared Ian; its not mongoid I know; now with 0.9 its the same beast; and I have a secret dont tell anyone they might freak out MM is quicker ssshhhhh. Merge it you know you wanna.

**Comment by ianwhite** [comment]
Hi,

I'm currently on holiday until the 1st May. I'll look at this after then. 

Cheers,
Ian White

**Comment by marclove** [comment]
+1 I could really use this.

Once it's accepted, I have a patch/pull request ready to add MongoMapper (0.9) support back to Devise.

**Comment by icidasset** [comment]
+1, I could use this too.

**Comment by brentd** [comment]
+1. No reason not to support MongoMapper in Devise anymore.

**Comment by ianwhite** [comment]
It's in 0.0.5

Thanks!

**Comment by icaruswings** [comment]
Awesome, thanks Ian, now off to get MM support back in devise

**Comment by foreverman** [comment]
+1. I need it.

**Pull request merged**
