### PR TITLE
Normalize _id to id for mongoid.

### PR DESCRIPTION
**Pull request by timgaleckas**
I wanted something like:
`NestedModel.to_adapter.find_first(parent_id: '2', id: '1')`
to be compliant with mongoid as well as active_record.

### CODE REVIEW

**Comment by ianwhite** [comment]
Hi Tim,

My first thought is that :id key is an implementation detail of the
orm.  This is why we support associations by object (leaving the
adapter to figure out how to determine the association key)

But I can see the value of your use case, scoped finding basically.
So I'm a bit torn.

If we do add :id normalisation for find_\* methods, this should be
added to the shared spec, and implemented in all adapters.

@josevalim what do you think?

Sent from my iPhone

On 12 Jun 2012, at 20:31, Tim Galeckas
reply@reply.github.com
wrote:

**Comment by josevalim** [comment]
I think this is reasonable. AFAIK, Active Record already does normalization (id will translate to whatever pkey you have).

**Comment by ianwhite** [comment]
Ok great.

Tim could you add a case to the shared example which does something
like find_first(:id => <n>, :other => 'condition')?

Cheers,
Ian

Sent from my iPhone

On 14 Jun 2012, at 11:32, "José Valim"
reply@reply.github.com
wrote:

**Comment by timgaleckas** [comment]
Test added. Take a look. Please forgive all the whitespace modifications. I have my vim autoclean on write.

**Pull request closed without merging**
