### PR TITLE
Add Sequel plugin

### PR DESCRIPTION
**Pull request by jeremyevans**
This plugin is based on the data_mapper plugin, modified to use
the Sequel API.  Sequel natively supports most features of
orm_adapter, only the association= method needs to be emulated.

### CODE REVIEW

**Comment by ianwhite** [comment]
Hi Jeremy,

I'm not sure that orm_adapter should patch Sequel to make it work.  I'd be surprised by that behaviour in an adapter plugin.  Also, the pull request contains no tests.

But, it's very easy to make your own gem `orm_adapter-sequel`, or similar.

Cheers,
Ian

**Comment by ianwhite** [comment]
My sincere apologies, I didn't see the specs for some reason, re-evaluating...

**Comment by ianwhite** [comment]
Hi Jeremy,

Really sorry about that, specs are all good.  Also, the adapter does't patch Sequel any more than any of the other adapters do.  

So, I'm happy with this patch.  José, any thoughts?

Cheers,
Ian

**Comment by ianwhite** [comment]
Hi Jeremy,
Is there a good reason not to use the existing `orm_adapter-sequel` gem?
As if you couldn't guess - I'm not a Sequel user :)
Cheers,
Ian

**Comment by jeremyevans** [comment]
Sorry, I wasn't aware of orm_adapter-sequel when I wrote the support.  Looking at it, it seems more complete than what I wrote, which basically is the minimum needed to pass the specs (I don't use orm_adapter myself).  I'll close this now.  Thanks for reviewing. :)

**Comment by ianwhite** [comment]
Hi Jeremy,

No worries, sorry about all the noise (not enough coffee before OSS...) and thanks for the other patch btw.

Cheers,
Ian

**Pull request closed without merging**
