### PR TITLE
Destroy and general fixes

### PR DESCRIPTION
**Pull request by fredwu**
Implemented `destroy()` :)

### CODE REVIEW

**Comment by josevalim** [comment]
Maybe we should receive the object to be deleted on destroy? This would give us more flexibility.

**Comment by fredwu** [comment]
@josevalim Could you clarify what you meant by this Jose? As in instead of `destroy(id)`, we do `destroy(object)`?

**Comment by josevalim** [comment]
> we do `destroy(object)`

Exactly.

**Comment by fredwu** [comment]
@josevalim Close to what you have in mind? :)

**Comment by josevalim** [comment]
Yup. @ianwhite wdyt?

**Comment by ianwhite** [comment]
José, fredwu,

Looks good, I'll look in more detail, and if all good, release.

(for some reason I'm not getting notified of these issue - until you mentioned me that is, hmmm...)

**Pull request merged**
