### PR TITLE
Support for ActiveResource (incl. tests)

### PR DESCRIPTION
**Pull request by lfittl**
Hi Ian,

When using devise I noticed that ActiveResource wasn't supported - we have a frontend Rails app that uses ActiveResource to access an internal backend API.

I've now added support for ActiveResource to orm_adapter, as this seems like the correct place.

I've also added tests, including a super-tiny Rails code base (shortened into 3 files) that serves as the ActiveResource backend server.

The tests are only enabled when you uncomment the rails and sqlite3 gem in the Gemfile (see comment there).

Let me know what you think & would be very happy to see these changes upstream.

Cheers,
Lukas

### CODE REVIEW

**Comment by RobertLowe** [comment]
Interesting!

**Comment by josevalim** [comment]
Could you please add support to activeresource on a gem? We want to keep orm adapter core small. Other ORMs support should be added via gems, thanks!

**Comment by stulentsev** [comment]
@lfittl What happened to your code? Is it available as a gem? I'd love to try it :)

**Comment by lfittl** [comment]
Just extracted it into a gem:

https://github.com/lfittl/orm_adapter_activeresource
https://rubygems.org/gems/orm_adapter_activeresource

Happy about forks & feedback.

**Pull request closed without merging**
