### PR TITLE
Get rid of deprecation warning about activerecord

### PR DESCRIPTION
**Pull request by ghost**
On Ubuntu (and probably in other places) a deprecation warning is generated if you require activerecord.

This update attempts to load active_record first, and then falls back to loading activerecord if that was unsuccessful. Before, it was the other way around.

Change tested and seems ok using Rails 3.2.0/Ruby 1.9.3 under Ubuntu 12.04.

### CODE REVIEW

**Comment by josevalim** [comment]
We should just remove the rescue clause altogether and stop supporting old active record versions.

**Comment by dxw** [comment]
I wasn't sure whether that was ok - figured that it might break some things. But yes, if it's not going to break people's stuff, I agree that would be better.

**Comment by josevalim** [comment]
If I am not wrong, that old format is deprecated since Rails 2.3, so I am fine with breaking compatibility on those ones.

**Comment by dxw** [comment]
Wow ok, yes. That's pretty old. Gimme 2 secs and I'll make a new pull request.

**Pull request closed without merging**
